apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-k8s-{{.Release.Name}}
  labels:
    app: hello-k8s
spec:
  replicas: {{.Values.replicas}}
  selector:
    matchLabels:
      app: hello-k8s
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hello-k8s
    spec:
      containers:
      - image: reg.qiniu.com/lixueli/hello-k8s:0.0.1
        name: hello-k8s
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: hello-k8s-{{.Release.Name}}
  labels:
    app: hello-k8s
spec:
  ports:
  - name: port-0
    port: 80
    protocol: TCP
    targetPort: 3003
  selector:
    app: hello-k8s
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello-k8s-{{.Release.Name}}
  annotations:
    qiniu.com/ingress-type: alb
spec:
  rules:
  - host: {{.Values.host}}
    http:
      paths:
      - backend:
          serviceName: hello-k8s-{{.Release.Name}}
          servicePort: 80
        path: /
